import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "../process/providers/Provider";

const BigShouldersDisplay = localFont({
  src: "./fonts/BigShouldersDisplay.ttf",
  variable: "--font-big-shoulders-display",
});

const Iceland = localFont({
  src: "./fonts/Iceland.ttf",
  variable: "--font-iceland",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`bg-black h-inherit ${BigShouldersDisplay.variable} ${Iceland.variable}`}>
        <Providers>
          {children}
        </Providers>
        <span className="fixed -right-64 -top-64 gradient size-[512px] pointer-events-none opacity-50" />
      </body>
    </html>
  );
}